//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qwerty.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("qwerty.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream laser1 {
            get {
                return ResourceManager.GetStream("laser1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream laser2 {
            get {
                return ResourceManager.GetStream("laser2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream laser3 {
            get {
                return ResourceManager.GetStream("laser3", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream laser4 {
            get {
                return ResourceManager.GetStream("laser4", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream spaceShipFly {
            get {
                return ResourceManager.GetStream("spaceShipFly", resourceCulture);
            }
        }
    }
}
